import * as ElfStruct from "../../../../src/binary-parser/types/elf/elf-structures";

export const mockedSections64: {
  Header: ElfStruct.Elf32_Shdr | ElfStruct.Elf64_Shdr;
  Name: string;
}[] = [
  {
    Header: {
      sh_addr: 0,
      sh_addralign: 0,
      sh_entsize: 0,
      sh_flags: 0,
      sh_info: 0,
      sh_link: 0,
      sh_name: 0,
      sh_offset: 0,
      sh_size: 0,
      sh_type: 0,
    },
    Name: "",
  },
  {
    Header: {
      sh_addr: 792,
      sh_addralign: 1,
      sh_entsize: 0,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 0,
      sh_name: 27,
      sh_offset: 792,
      sh_size: 28,
      sh_type: 1,
    },
    Name: ".interp",
  },
  {
    Header: {
      sh_addr: 824,
      sh_addralign: 8,
      sh_entsize: 0,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 0,
      sh_name: 35,
      sh_offset: 824,
      sh_size: 32,
      sh_type: 7,
    },
    Name: ".note.gnu.property",
  },
  {
    Header: {
      sh_addr: 856,
      sh_addralign: 4,
      sh_entsize: 0,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 0,
      sh_name: 54,
      sh_offset: 856,
      sh_size: 36,
      sh_type: 7,
    },
    Name: ".note.gnu.build-id",
  },
  {
    Header: {
      sh_addr: 892,
      sh_addralign: 4,
      sh_entsize: 0,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 0,
      sh_name: 73,
      sh_offset: 892,
      sh_size: 32,
      sh_type: 7,
    },
    Name: ".note.ABI-tag",
  },
  {
    Header: {
      sh_addr: 928,
      sh_addralign: 8,
      sh_entsize: 0,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 6,
      sh_name: 87,
      sh_offset: 928,
      sh_size: 36,
      sh_type: 1879048182,
    },
    Name: ".gnu.hash",
  },
  {
    Header: {
      sh_addr: 968,
      sh_addralign: 8,
      sh_entsize: 24,
      sh_flags: 2,
      sh_info: 1,
      sh_link: 7,
      sh_name: 97,
      sh_offset: 968,
      sh_size: 168,
      sh_type: 11,
    },
    Name: ".dynsym",
  },
  {
    Header: {
      sh_addr: 1136,
      sh_addralign: 1,
      sh_entsize: 0,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 0,
      sh_name: 105,
      sh_offset: 1136,
      sh_size: 130,
      sh_type: 3,
    },
    Name: ".dynstr",
  },
  {
    Header: {
      sh_addr: 1266,
      sh_addralign: 2,
      sh_entsize: 2,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 6,
      sh_name: 113,
      sh_offset: 1266,
      sh_size: 14,
      sh_type: 1879048191,
    },
    Name: ".gnu.version",
  },
  {
    Header: {
      sh_addr: 1280,
      sh_addralign: 8,
      sh_entsize: 0,
      sh_flags: 2,
      sh_info: 1,
      sh_link: 7,
      sh_name: 126,
      sh_offset: 1280,
      sh_size: 32,
      sh_type: 1879048190,
    },
    Name: ".gnu.version_r",
  },
  {
    Header: {
      sh_addr: 1312,
      sh_addralign: 8,
      sh_entsize: 24,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 6,
      sh_name: 141,
      sh_offset: 1312,
      sh_size: 192,
      sh_type: 4,
    },
    Name: ".rela.dyn",
  },
  {
    Header: {
      sh_addr: 1504,
      sh_addralign: 8,
      sh_entsize: 24,
      sh_flags: 66,
      sh_info: 24,
      sh_link: 6,
      sh_name: 151,
      sh_offset: 1504,
      sh_size: 24,
      sh_type: 4,
    },
    Name: ".rela.plt",
  },
  {
    Header: {
      sh_addr: 4096,
      sh_addralign: 4,
      sh_entsize: 0,
      sh_flags: 6,
      sh_info: 0,
      sh_link: 0,
      sh_name: 161,
      sh_offset: 4096,
      sh_size: 27,
      sh_type: 1,
    },
    Name: ".init",
  },

  {
    Header: {
      sh_addr: 4128,
      sh_addralign: 16,
      sh_entsize: 16,
      sh_flags: 6,
      sh_info: 0,
      sh_link: 0,
      sh_name: 156,
      sh_offset: 4128,
      sh_size: 32,
      sh_type: 1,
    },
    Name: ".plt",
  },
  {
    Header: {
      sh_addr: 4160,
      sh_addralign: 16,
      sh_entsize: 16,
      sh_flags: 6,
      sh_info: 0,
      sh_link: 0,
      sh_name: 167,
      sh_offset: 4160,
      sh_size: 16,
      sh_type: 1,
    },
    Name: ".plt.got",
  },
  {
    Header: {
      sh_addr: 4176,
      sh_addralign: 16,
      sh_entsize: 16,
      sh_flags: 6,
      sh_info: 0,
      sh_link: 0,
      sh_name: 176,
      sh_offset: 4176,
      sh_size: 16,
      sh_type: 1,
    },
    Name: ".plt.sec",
  },
  {
    Header: {
      sh_addr: 4192,
      sh_addralign: 16,
      sh_entsize: 0,
      sh_flags: 6,
      sh_info: 0,
      sh_link: 0,
      sh_name: 185,
      sh_offset: 4192,
      sh_size: 389,
      sh_type: 1,
    },
    Name: ".text",
  },
  {
    Header: {
      sh_addr: 4584,
      sh_addralign: 4,
      sh_entsize: 0,
      sh_flags: 6,
      sh_info: 0,
      sh_link: 0,
      sh_name: 191,
      sh_offset: 4584,
      sh_size: 13,
      sh_type: 1,
    },
    Name: ".fini",
  },
  {
    Header: {
      sh_addr: 8192,
      sh_addralign: 4,
      sh_entsize: 0,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 0,
      sh_name: 197,
      sh_offset: 8192,
      sh_size: 17,
      sh_type: 1,
    },
    Name: ".rodata",
  },
  {
    Header: {
      sh_addr: 8212,
      sh_addralign: 4,
      sh_entsize: 0,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 0,
      sh_name: 205,
      sh_offset: 8212,
      sh_size: 68,
      sh_type: 1,
    },
    Name: ".eh_frame_hdr",
  },
  {
    Header: {
      sh_addr: 8280,
      sh_addralign: 8,
      sh_entsize: 0,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 0,
      sh_name: 219,
      sh_offset: 8280,
      sh_size: 264,
      sh_type: 1,
    },
    Name: ".eh_frame",
  },
  {
    Header: {
      sh_addr: 15800,
      sh_addralign: 8,
      sh_entsize: 8,
      sh_flags: 3,
      sh_info: 0,
      sh_link: 0,
      sh_name: 229,
      sh_offset: 11704,
      sh_size: 8,
      sh_type: 14,
    },
    Name: ".init_array",
  },
  {
    Header: {
      sh_addr: 15808,
      sh_addralign: 8,
      sh_entsize: 8,
      sh_flags: 3,
      sh_info: 0,
      sh_link: 0,
      sh_name: 241,
      sh_offset: 11712,
      sh_size: 8,
      sh_type: 15,
    },
    Name: ".fini_array",
  },
  {
    Header: {
      sh_addr: 15816,
      sh_addralign: 8,
      sh_entsize: 16,
      sh_flags: 3,
      sh_info: 0,
      sh_link: 7,
      sh_name: 253,
      sh_offset: 11720,
      sh_size: 496,
      sh_type: 6,
    },
    Name: ".dynamic",
  },
  {
    Header: {
      sh_addr: 16312,
      sh_addralign: 8,
      sh_entsize: 8,
      sh_flags: 3,
      sh_info: 0,
      sh_link: 0,
      sh_name: 171,
      sh_offset: 12216,
      sh_size: 72,
      sh_type: 1,
    },
    Name: ".got",
  },
  {
    Header: {
      sh_addr: 16384,
      sh_addralign: 8,
      sh_entsize: 0,
      sh_flags: 3,
      sh_info: 0,
      sh_link: 0,
      sh_name: 262,
      sh_offset: 12288,
      sh_size: 16,
      sh_type: 1,
    },
    Name: ".data",
  },
  {
    Header: {
      sh_addr: 16400,
      sh_addralign: 1,
      sh_entsize: 0,
      sh_flags: 3,
      sh_info: 0,
      sh_link: 0,
      sh_name: 268,
      sh_offset: 12304,
      sh_size: 8,
      sh_type: 8,
    },
    Name: ".bss",
  },
  {
    Header: {
      sh_addr: 0,
      sh_addralign: 1,
      sh_entsize: 1,
      sh_flags: 48,
      sh_info: 0,
      sh_link: 0,
      sh_name: 273,
      sh_offset: 12304,
      sh_size: 43,
      sh_type: 1,
    },
    Name: ".comment",
  },
  {
    Header: {
      sh_addr: 0,
      sh_addralign: 8,
      sh_entsize: 24,
      sh_flags: 0,
      sh_info: 46,
      sh_link: 29,
      sh_name: 1,
      sh_offset: 12352,
      sh_size: 1560,
      sh_type: 2,
    },
    Name: ".symtab",
  },
  {
    Header: {
      sh_addr: 0,
      sh_addralign: 1,
      sh_entsize: 0,
      sh_flags: 0,
      sh_info: 0,
      sh_link: 0,
      sh_name: 9,
      sh_offset: 13912,
      sh_size: 515,
      sh_type: 3,
    },
    Name: ".strtab",
  },
  {
    Header: {
      sh_addr: 0,
      sh_addralign: 1,
      sh_entsize: 0,
      sh_flags: 0,
      sh_info: 0,
      sh_link: 0,
      sh_name: 17,
      sh_offset: 14427,
      sh_size: 282,
      sh_type: 3,
    },
    Name: ".shstrtab",
  },
];

export const mockedSections32: {
  Header: ElfStruct.Elf32_Shdr | ElfStruct.Elf64_Shdr;
  Name: string;
}[] = [
  {
    Header: {
      sh_addr: 0,
      sh_addralign: 0,
      sh_entsize: 0,
      sh_flags: 0,
      sh_info: 0,
      sh_link: 0,
      sh_name: 0,
      sh_offset: 0,
      sh_size: 0,
      sh_type: 0,
    },
    Name: "",
  },
  {
    Header: {
      sh_addr: 340,
      sh_addralign: 1,
      sh_entsize: 0,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 0,
      sh_name: 27,
      sh_offset: 340,
      sh_size: 25,
      sh_type: 1,
    },
    Name: ".interp",
  },
  {
    Header: {
      sh_addr: 368,
      sh_addralign: 4,
      sh_entsize: 0,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 0,
      sh_name: 35,
      sh_offset: 368,
      sh_size: 36,
      sh_type: 7,
    },
    Name: ".note.gnu.build-id",
  },
  {
    Header: {
      sh_addr: 404,
      sh_addralign: 4,
      sh_entsize: 0,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 0,
      sh_name: 54,
      sh_offset: 404,
      sh_size: 32,
      sh_type: 7,
    },
    Name: ".note.ABI-tag",
  },
  {
    Header: {
      sh_addr: 436,
      sh_addralign: 4,
      sh_entsize: 4,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 5,
      sh_name: 68,
      sh_offset: 436,
      sh_size: 24,
      sh_type: 1879048182,
    },
    Name: ".gnu.hash",
  },
  {
    Header: {
      sh_addr: 460,
      sh_addralign: 4,
      sh_entsize: 16,
      sh_flags: 2,
      sh_info: 3,
      sh_link: 6,
      sh_name: 78,
      sh_offset: 460,
      sh_size: 160,
      sh_type: 11,
    },
    Name: ".dynsym",
  },
  {
    Header: {
      sh_addr: 620,
      sh_addralign: 1,
      sh_entsize: 0,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 0,
      sh_name: 86,
      sh_offset: 620,
      sh_size: 134,
      sh_type: 3,
    },
    Name: ".dynstr",
  },
  {
    Header: {
      sh_addr: 754,
      sh_addralign: 2,
      sh_entsize: 2,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 5,
      sh_name: 94,
      sh_offset: 754,
      sh_size: 20,
      sh_type: 1879048191,
    },
    Name: ".gnu.version",
  },
  {
    Header: {
      sh_addr: 776,
      sh_addralign: 4,
      sh_entsize: 0,
      sh_flags: 2,
      sh_info: 1,
      sh_link: 6,
      sh_name: 107,
      sh_offset: 776,
      sh_size: 32,
      sh_type: 1879048190,
    },
    Name: ".gnu.version_r",
  },
  {
    Header: {
      sh_addr: 808,
      sh_addralign: 4,
      sh_entsize: 8,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 5,
      sh_name: 122,
      sh_offset: 808,
      sh_size: 80,
      sh_type: 9,
    },
    Name: ".rel.dyn",
  },
  {
    Header: {
      sh_addr: 888,
      sh_addralign: 4,
      sh_entsize: 8,
      sh_flags: 66,
      sh_info: 21,
      sh_link: 5,
      sh_name: 131,
      sh_offset: 888,
      sh_size: 40,
      sh_type: 9,
    },
    Name: ".rel.plt",
  },
  {
    Header: {
      sh_addr: 928,
      sh_addralign: 4,
      sh_entsize: 0,
      sh_flags: 6,
      sh_info: 0,
      sh_link: 0,
      sh_name: 140,
      sh_offset: 928,
      sh_size: 12,
      sh_type: 1,
    },
    Name: ".init",
  },
  {
    Header: {
      sh_addr: 940,
      sh_addralign: 4,
      sh_entsize: 4,
      sh_flags: 6,
      sh_info: 0,
      sh_link: 0,
      sh_name: 135,
      sh_offset: 940,
      sh_size: 80,
      sh_type: 1,
    },
    Name: ".plt",
  },
  {
    Header: {
      sh_addr: 1020,
      sh_addralign: 4,
      sh_entsize: 0,
      sh_flags: 6,
      sh_info: 0,
      sh_link: 0,
      sh_name: 146,
      sh_offset: 1020,
      sh_size: 364,
      sh_type: 1,
    },
    Name: ".text",
  },
  {
    Header: {
      sh_addr: 1384,
      sh_addralign: 4,
      sh_entsize: 0,
      sh_flags: 6,
      sh_info: 0,
      sh_link: 0,
      sh_name: 152,
      sh_offset: 1384,
      sh_size: 8,
      sh_type: 1,
    },
    Name: ".fini",
  },
  {
    Header: {
      sh_addr: 1392,
      sh_addralign: 4,
      sh_entsize: 0,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 0,
      sh_name: 158,
      sh_offset: 1392,
      sh_size: 17,
      sh_type: 1,
    },
    Name: ".rodata",
  },
  {
    Header: {
      sh_addr: 1412,
      sh_addralign: 4,
      sh_entsize: 0,
      sh_flags: 130,
      sh_info: 0,
      sh_link: 13,
      sh_name: 166,
      sh_offset: 1412,
      sh_size: 8,
      sh_type: 1879048193,
    },
    Name: ".ARM.exidx",
  },
  {
    Header: {
      sh_addr: 1420,
      sh_addralign: 4,
      sh_entsize: 0,
      sh_flags: 2,
      sh_info: 0,
      sh_link: 0,
      sh_name: 177,
      sh_offset: 1420,
      sh_size: 4,
      sh_type: 1,
    },
    Name: ".eh_frame",
  },
  {
    Header: {
      sh_addr: 69316,
      sh_addralign: 4,
      sh_entsize: 4,
      sh_flags: 3,
      sh_info: 0,
      sh_link: 0,
      sh_name: 187,
      sh_offset: 3780,
      sh_size: 4,
      sh_type: 14,
    },
    Name: ".init_array",
  },
  {
    Header: {
      sh_addr: 69320,
      sh_addralign: 4,
      sh_entsize: 4,
      sh_flags: 3,
      sh_info: 0,
      sh_link: 0,
      sh_name: 199,
      sh_offset: 3784,
      sh_size: 4,
      sh_type: 15,
    },
    Name: ".fini_array",
  },
  {
    Header: {
      sh_addr: 69324,
      sh_addralign: 4,
      sh_entsize: 8,
      sh_flags: 3,
      sh_info: 0,
      sh_link: 6,
      sh_name: 211,
      sh_offset: 3788,
      sh_size: 248,
      sh_type: 6,
    },
    Name: ".dynamic",
  },
  {
    Header: {
      sh_addr: 69572,
      sh_addralign: 4,
      sh_entsize: 4,
      sh_flags: 3,
      sh_info: 0,
      sh_link: 0,
      sh_name: 220,
      sh_offset: 4036,
      sh_size: 60,
      sh_type: 1,
    },
    Name: ".got",
  },
  {
    Header: {
      sh_addr: 69632,
      sh_addralign: 4,
      sh_entsize: 0,
      sh_flags: 3,
      sh_info: 0,
      sh_link: 0,
      sh_name: 225,
      sh_offset: 4096,
      sh_size: 8,
      sh_type: 1,
    },
    Name: ".data",
  },
  {
    Header: {
      sh_addr: 69640,
      sh_addralign: 1,
      sh_entsize: 0,
      sh_flags: 3,
      sh_info: 0,
      sh_link: 0,
      sh_name: 231,
      sh_offset: 4104,
      sh_size: 4,
      sh_type: 8,
    },
    Name: ".bss",
  },
  {
    Header: {
      sh_addr: 0,
      sh_addralign: 1,
      sh_entsize: 1,
      sh_flags: 48,
      sh_info: 0,
      sh_link: 0,
      sh_name: 236,
      sh_offset: 4104,
      sh_size: 43,
      sh_type: 1,
    },
    Name: ".comment",
  },
  {
    Header: {
      sh_addr: 0,
      sh_addralign: 1,
      sh_entsize: 0,
      sh_flags: 0,
      sh_info: 0,
      sh_link: 0,
      sh_name: 245,
      sh_offset: 4147,
      sh_size: 51,
      sh_type: 1879048195,
    },
    Name: ".ARM.attributes",
  },
  {
    Header: {
      sh_addr: 0,
      sh_addralign: 4,
      sh_entsize: 16,
      sh_flags: 0,
      sh_info: 81,
      sh_link: 27,
      sh_name: 1,
      sh_offset: 4200,
      sh_size: 1680,
      sh_type: 2,
    },
    Name: ".symtab",
  },
  {
    Header: {
      sh_addr: 0,
      sh_addralign: 1,
      sh_entsize: 0,
      sh_flags: 0,
      sh_info: 0,
      sh_link: 0,
      sh_name: 9,
      sh_offset: 5880,
      sh_size: 850,
      sh_type: 3,
    },
    Name: ".strtab",
  },
  {
    Header: {
      sh_addr: 0,
      sh_addralign: 1,
      sh_entsize: 0,
      sh_flags: 0,
      sh_info: 0,
      sh_link: 0,
      sh_name: 17,
      sh_offset: 6730,
      sh_size: 261,
      sh_type: 3,
    },
    Name: ".shstrtab",
  },
];

export const mockedPrograms64: (ElfStruct.Elf32_Phdr | ElfStruct.Elf64_Phdr)[] = [
  {
    p_align: 8,
    p_filesz: 728,
    p_flags: 4,
    p_memsz: 728,
    p_offset: 64,
    p_paddr: 64,
    p_type: 6,
    p_vaddr: 64,
  },
  {
    p_align: 1,
    p_filesz: 28,
    p_flags: 4,
    p_memsz: 28,
    p_offset: 792,
    p_paddr: 792,
    p_type: 3,
    p_vaddr: 792,
  },
  {
    p_align: 4096,
    p_filesz: 1528,
    p_flags: 4,
    p_memsz: 1528,
    p_offset: 0,
    p_paddr: 0,
    p_type: 1,
    p_vaddr: 0,
  },
  {
    p_align: 4096,
    p_filesz: 501,
    p_flags: 5,
    p_memsz: 501,
    p_offset: 4096,
    p_paddr: 4096,
    p_type: 1,
    p_vaddr: 4096,
  },
  {
    p_align: 4096,
    p_filesz: 352,
    p_flags: 4,
    p_memsz: 352,
    p_offset: 8192,
    p_paddr: 8192,
    p_type: 1,
    p_vaddr: 8192,
  },
  {
    p_align: 4096,
    p_filesz: 600,
    p_flags: 6,
    p_memsz: 608,
    p_offset: 11704,
    p_paddr: 15800,
    p_type: 1,
    p_vaddr: 15800,
  },
  {
    p_align: 8,
    p_filesz: 496,
    p_flags: 6,
    p_memsz: 496,
    p_offset: 11720,
    p_paddr: 15816,
    p_type: 2,
    p_vaddr: 15816,
  },
  {
    p_align: 8,
    p_filesz: 32,
    p_flags: 4,
    p_memsz: 32,
    p_offset: 824,
    p_paddr: 824,
    p_type: 4,
    p_vaddr: 824,
  },
  {
    p_align: 4,
    p_filesz: 68,
    p_flags: 4,
    p_memsz: 68,
    p_offset: 856,
    p_paddr: 856,
    p_type: 4,
    p_vaddr: 856,
  },
  {
    p_align: 8,
    p_filesz: 32,
    p_flags: 4,
    p_memsz: 32,
    p_offset: 824,
    p_paddr: 824,
    p_type: 1685382483,
    p_vaddr: 824,
  },
  {
    p_align: 4,
    p_filesz: 68,
    p_flags: 4,
    p_memsz: 68,
    p_offset: 8212,
    p_paddr: 8212,
    p_type: 1685382480,
    p_vaddr: 8212,
  },
  {
    p_align: 16,
    p_filesz: 0,
    p_flags: 6,
    p_memsz: 0,
    p_offset: 0,
    p_paddr: 0,
    p_type: 1685382481,
    p_vaddr: 0,
  },
  {
    p_align: 1,
    p_filesz: 584,
    p_flags: 4,
    p_memsz: 584,
    p_offset: 11704,
    p_paddr: 15800,
    p_type: 1685382482,
    p_vaddr: 15800,
  },
];

export const mockedPrograms32: (ElfStruct.Elf32_Phdr | ElfStruct.Elf64_Phdr)[] = [
  {
    p_align: 4,
    p_filesz: 8,
    p_flags: 4,
    p_memsz: 8,
    p_offset: 1412,
    p_paddr: 1412,
    p_type: 1879048193,
    p_vaddr: 1412,
  },
  {
    p_align: 4,
    p_filesz: 288,
    p_flags: 4,
    p_memsz: 288,
    p_offset: 52,
    p_paddr: 52,
    p_type: 6,
    p_vaddr: 52,
  },
  {
    p_align: 1,
    p_filesz: 25,
    p_flags: 4,
    p_memsz: 25,
    p_offset: 340,
    p_paddr: 340,
    p_type: 3,
    p_vaddr: 340,
  },
  {
    p_align: 65536,
    p_filesz: 1424,
    p_flags: 5,
    p_memsz: 1424,
    p_offset: 0,
    p_paddr: 0,
    p_type: 1,
    p_vaddr: 0,
  },
  {
    p_align: 65536,
    p_filesz: 324,
    p_flags: 6,
    p_memsz: 328,
    p_offset: 3780,
    p_paddr: 69316,
    p_type: 1,
    p_vaddr: 69316,
  },
  {
    p_align: 4,
    p_filesz: 248,
    p_flags: 6,
    p_memsz: 248,
    p_offset: 3788,
    p_paddr: 69324,
    p_type: 2,
    p_vaddr: 69324,
  },
  {
    p_align: 4,
    p_filesz: 68,
    p_flags: 4,
    p_memsz: 68,
    p_offset: 368,
    p_paddr: 368,
    p_type: 4,
    p_vaddr: 368,
  },
  {
    p_align: 16,
    p_filesz: 0,
    p_flags: 6,
    p_memsz: 0,
    p_offset: 0,
    p_paddr: 0,
    p_type: 1685382481,
    p_vaddr: 0,
  },
  {
    p_align: 1,
    p_filesz: 316,
    p_flags: 4,
    p_memsz: 316,
    p_offset: 3780,
    p_paddr: 69316,
    p_type: 1685382482,
    p_vaddr: 69316,
  },
];
