name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  ci-cd-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Execute Permissions
        run: chmod -R +x ./scripts

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/elf-ripper/elf-ripper-dev-test-env:latest

      - name: Run Tests
        id: run-tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            ghcr.io/elf-ripper/elf-ripper-dev-test-env:latest \
            bash -c "./scripts/tester.sh"

      - name: Package VSCode Extension
        id: package-extension
        if: steps.run-tests.outcome == 'success'
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            ghcr.io/elf-ripper/elf-ripper-dev-test-env:latest \
            bash -c "./scripts/packager.sh"

      - name: Upload Packaged Extension
        if: steps.package-extension.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: vsix-package
          path: "*.vsix"
