name: Build and Push Docker Image


on:
  push:
    branches:
      - main
    paths:
      - ".devcontainer/Dockerfile"
      - ".github/workflows/docker-image-update.yml"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/hmfcpt/elf-ripper-dev-test-env:latest -f .devcontainer/Dockerfile .

      - name: Push Docker image
        run: |
          docker push ghcr.io/hmfcpt/elf-ripper-dev-test-env:latest
